# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'permissions': (('can_undelete', 'Can undelete this object'),),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'permissions': (('can_undelete', 'Can undelete this object'),),
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Parent'),
        ),
    ]
